### ISSUE TITLE
(Not a issue) Sugguestion for decompiling

### ISSUE THREAD

**Issue by Meowcat285** [userlandkernel/ios-unstripped-kexts#1]
I recomend using Ghidra for decompiling, its better at auto anaylisis then IDA pro, it is multiplatform and it has a nice project system. Best of all its made by the NSA! [Link to page](https://ghidra-sre.org/)

**Comment by userlandkernel** [comment]
You are very right, but I don't like getting out of my comfort zone.

**Comment by userlandkernel** [comment]
Alright I have been playing around with Ghidra and must conclude it is fairly easy to learn (also thanks to the demo and help included with it).
Ghidra offers all I need as a reverse engineer, the pseudocode looks sometimes even better than in the IDA. I'll follow your advice as it's really great open-source software. Thanks NSA!
